import Provider from '@/provider/Provider';
import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'News',
  description: 'Generated by Rhonald Capera',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang='es' suppressHydrationWarning={true}>
      <body className={inter.className} style={{ margin: 0 }}>
        <Provider>{children}</Provider>
      </body>
    </html>
  );
}
